DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    "ID" BINARY PRIMARY KEY NOT NULL,
    "CREATED" TIMESTAMP,
    "EMAIL" VARCHAR(255),
    "ISACTIVE" BOOLEAN,
    "LAST_LOGIN" TIMESTAMP,
    "MODIFIED" TIMESTAMP,
    "NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "TOKEN" VARCHAR(255)
);

DROP TABLE IF EXISTS PHONES;

CREATE TABLE PHONES(
    "NUMBER" VARCHAR(255) NOT NULL,
    "CITYCODE" VARCHAR(255),
    "COUNTRYCODE" VARCHAR(255),
    "USER_ID" BINARY,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);